#!/bin/bash
cd /var/www/lostastronaut/pixigame/
chown root:root cache/logs/last*.txt
chmod a+rwx cache/logs/last*.txt
rm -rf cache/logs/last-last-log.txt
mv cache/logs/last-log.txt cache/logs/last-last-log.txt
